filetype plugin on
filetype indent on

set nohidden
set nobackup
set nowritebackup
set noswapfile
set autoread
set autowriteall
set history=9000
set undolevels=500
set undofile
set undodir=~/.vimundo

if isdirectory($HOME . '/.vimundo') == 0
	call mkdir($HOME.'/.vimundo', 'p')
endif

set mouse=
set ttymouse=sgr
set updatetime=500
set balloondelay=250
set signcolumn=no
set scrolloff=999
set virtualedit=block,onemore

set clipboard=unnamed

set nocursorline
set showmatch
set mat=1
set ruler
set list
set listchars=tab:▸\ ,trail:•,extends:»,precedes:«,nbsp:␣

set noerrorbells
set novisualbell
set t_vb=

set lazyredraw
set ttyfast

set splitbelow
set splitright

set incsearch
set hlsearch
set ignorecase
set nowrapscan
set gdefault

set wildmenu
set wildignore+=*/node_modules/*,*/vendor/*

set foldenable
set foldlevelstart=10
set foldnestmax=20
set foldmethod=syntax

set textwidth=79
set colorcolumn=0
set nowrap
set linebreak
set breakindent

let g:netrw_banner = 0
let g:netrw_keepdir = 0
let g:netrw_liststyle = 1
let g:netrw_sort_options = 'i'

set exrc
set secure

set autoindent
set smartindent

set backspace=indent,eol,start

set laststatus=2

set omnifunc=syntaxcomplete#Complete
set completeopt=menuone,noinsert,noselect
set shortmess+=c

set tags=./tags,tags

set grepprg=rg\ --vimgrep\ $*
set grepformat=%f:%l:%c:%m

command! -nargs=* G grep <args> | cwindow
command! -nargs=* E edit **/<args>

let mapleader = " "

inoremap jk <Esc>
nnoremap j gj
nnoremap k gk
nnoremap ; :
vnoremap ; :
nnoremap L $
nnoremap H ^
nnoremap Q q
nnoremap q :close<CR>
nnoremap g= mzgg=G`zzz
xnoremap <  <gv
xnoremap >  >gv
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprev<CR>
nnoremap <C-q> :bd<CR>


noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>
inoremap <Up> <nop>
inoremap <Down> <nop>
inoremap <Left> <nop>
inoremap <Right> <nop>

augroup dispatch_settings
	autocmd!
	autocmd FileType go let b:dispatch = 'goimports -w %'
	autocmd FileType go compiler go
	autocmd FileType nix let b:dispatch = 'nixfmt %'
	autocmd FileType nix compiler nix-build
	autocmd FileType py compiler flake8
augroup end

imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)

if has('conceal')
	set conceallevel=2 concealcursor=niv
endif

let g:neosnippet#snippets_directory='~/.vim/snippets'

set notermguicolors
set t_Co=16
set t_ut=

highlight clear
highlight LineNr NONE

syntax off
