export PATH=$PATH:~/go/bin:~/bin

alias e=emacsclient
alias k=kubectl
alias kgp=kubectl get pods
alias p=pass
alias df=df -h
alias rebuild='sudo nixos-rebuild switch'

(cat ~/.cache/wal/sequences &)
cat ~/.cache/wal/sequences
source ~/.cache/wal/colors-tty.sh
