export PATH=$PATH:~/go/bin
export WINEARCH=win32
export EDITOR=vim

alias v=vim
alias e=emacsclient
alias k=kubectl
alias kgp=kubectl get pods
alias p=pass
alias df=df -h
alias rebuild='sudo nixos-rebuild switch'

(cat ~/.cache/wal/sequences &)
cat ~/.cache/wal/sequences
source ~/.cache/wal/colors-tty.sh
