filetype plugin on
filetype indent on

set nohidden
set nobackup
set nowritebackup
set noswapfile
set autoread
set autowriteall
set history=9000
set undolevels=500
set undofile
set undodir=~/.vimundo

if isdirectory($HOME . '/.vimundo') == 0
	call mkdir($HOME.'/.vimundo', 'p')
endif

set viminfo+=n~/.vim/viminfo

set mouse=
set ttymouse=sgr
set updatetime=500
set balloondelay=250
set signcolumn=no
set scrolloff=999
set virtualedit=block,onemore

set clipboard=unnamed

set nocursorline
set showmatch
set mat=1
set ruler
set list
set listchars=tab:▸\ ,trail:•,extends:»,precedes:«,nbsp:␣

set noerrorbells
set novisualbell
set t_vb=

set lazyredraw
set ttyfast

set splitbelow
set splitright

set incsearch
set hlsearch
set ignorecase
set nowrapscan
set gdefault

set wildmenu
set wildignore+=*/node_modules/*,*/vendor/*

set foldenable
set foldlevelstart=10
set foldnestmax=20
set foldmethod=syntax

set textwidth=79
set colorcolumn=0
set nowrap
set linebreak
set breakindent

let g:netrw_banner = 0
let g:netrw_keepdir = 0
let g:netrw_liststyle = 1
let g:netrw_sort_options = 'i'

set exrc
set secure

set autoindent
set smartindent

set backspace=indent,eol,start

set laststatus=2

set omnifunc=syntaxcomplete#Complete
set completeopt=menuone,noinsert,noselect
set shortmess+=c

set tags=./tags,tags

set grepprg=rg\ --vimgrep\ $*
set grepformat=%f:%l:%c:%m

command! -nargs=* Grep grep <args> | cwindow

let mapleader = " "

inoremap jk <Esc>
nnoremap j gj
nnoremap k gk
nnoremap ; :
vnoremap ; :
nnoremap L $
nnoremap H ^
nnoremap g= mzgg=G`zzz
xnoremap <  <gv
xnoremap >  >gv
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprev<CR>
nnoremap c* *``cgn
nnoremap c# #``cgN

colorscheme default
